spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/library-core
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  logging:
    file:
      name: ./logs/library-log.log
    level:
      sql: debug